yarnPath: .yarn/releases/yarn-3.1.1.cjs
nodeLinker: node-modules
npmScopes:
  anulman:
    npmRegistryServer: "https://npm.pkg.github.com"
    # Github Personal Access Token that _must_ have at least `read:packages` perms
    npmAuthToken: "${GITHUB_PAT}"
